"""initial

Revision ID: 93e4643116c1
Revises: 
Create Date: 2026-03-15 12:45:27.117659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e4643116c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_ticket', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=200), nullable=False),
    sa.Column('municipio', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'llamando', 'no_contesto', 'reintento_pendiente', 'completado', 'fallido', name='estado_ticket'), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_estado'), 'tickets', ['estado'], unique=False)
    op.create_index(op.f('ix_tickets_numero_ticket'), 'tickets', ['numero_ticket'], unique=True)
    op.create_table('llamadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('call_sid', sa.String(length=100), nullable=True),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('terminada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sid')
    )
    op.create_index(op.f('ix_llamadas_ticket_id'), 'llamadas', ['ticket_id'], unique=False)
    op.create_table('respuestas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('llamada_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llamada_id'], ['llamadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuestas_llamada_id'), 'respuestas', ['llamada_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respuestas_llamada_id'), table_name='respuestas')
    op.drop_table('respuestas')
    op.drop_index(op.f('ix_llamadas_ticket_id'), table_name='llamadas')
    op.drop_table('llamadas')
    op.drop_index(op.f('ix_tickets_numero_ticket'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_estado'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
