"""add mensajes_llamada

Revision ID: 97da187dbd36
Revises: 93e4643116c1
Create Date: 2026-03-15 12:50:45.125131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97da187dbd36'
down_revision: Union[str, Sequence[str], None] = '93e4643116c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensajes_llamada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('llamada_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('registrado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llamada_id'], ['llamadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_llamada_llamada_id'), 'mensajes_llamada', ['llamada_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_llamada_llamada_id'), table_name='mensajes_llamada')
    op.drop_table('mensajes_llamada')
    # ### end Alembic commands ###
